spring.application.name=meetball

# Database Configuration (H2 In-Memory)
spring.datasource.url=jdbc:h2:mem:meetball_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console Configuration (Access at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Google Client ID Placeholder (Must match your Frontend Client ID)
google.client.id=875769361485-fv0ftg781tnpodgcd24b5jaalkuou7v7.apps.googleusercontent.com

# Seed Data Initialization (Enabled for local tests by default)
app.seed.enabled=true
