spring.application.name=meetball
server.port=${PORT:8080}
spring.profiles.default=prod

spring.jpa.open-in-view=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

google.client.id=${GOOGLE_CLIENT_ID:}

spring.servlet.multipart.max-file-size=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:50MB}

# Storage Configuration
app.storage.type=${APP_STORAGE_TYPE:local}
app.upload-dir=uploads/

# AWS S3 Configuration
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET:}
spring.cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:}
